[2024-01-06T14:24:43.087-0800] {processor.py:161} INFO - Started process (PID=7111) to work on /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:24:43.088-0800] {processor.py:830} INFO - Processing file /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-06T14:24:43.089-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:24:43.089-0800] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:24:43.092-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:24:43.092-0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-06T14:24:43.092-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:24:43.092-0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-06T14:24:43.093-0800] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:24:43.117-0800] {processor.py:183} INFO - Processing /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-01-06T14:25:13.197-0800] {processor.py:161} INFO - Started process (PID=7267) to work on /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:25:13.198-0800] {processor.py:830} INFO - Processing file /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-06T14:25:13.199-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:25:13.199-0800] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:25:13.202-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:25:13.202-0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-06T14:25:13.202-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:25:13.202-0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-06T14:25:13.202-0800] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:25:13.228-0800] {processor.py:183} INFO - Processing /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-01-06T14:25:43.285-0800] {processor.py:161} INFO - Started process (PID=7512) to work on /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:25:43.286-0800] {processor.py:830} INFO - Processing file /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-06T14:25:43.287-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:25:43.286-0800] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:25:43.290-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:25:43.290-0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-06T14:25:43.290-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:25:43.290-0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-06T14:25:43.290-0800] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:25:43.315-0800] {processor.py:183} INFO - Processing /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-01-06T14:26:13.610-0800] {processor.py:161} INFO - Started process (PID=8052) to work on /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:26:13.611-0800] {processor.py:830} INFO - Processing file /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-06T14:26:13.612-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:26:13.612-0800] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:26:13.616-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:26:13.615-0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-06T14:26:13.616-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:26:13.616-0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-06T14:26:13.616-0800] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:26:13.641-0800] {processor.py:183} INFO - Processing /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-01-06T14:35:54.758-0800] {processor.py:161} INFO - Started process (PID=9565) to work on /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:35:54.759-0800] {processor.py:830} INFO - Processing file /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-06T14:35:54.760-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:35:54.760-0800] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:35:54.764-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:35:54.763-0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-06T14:35:54.764-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:35:54.764-0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-06T14:35:54.764-0800] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:35:54.789-0800] {processor.py:183} INFO - Processing /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-01-06T14:36:24.841-0800] {processor.py:161} INFO - Started process (PID=9748) to work on /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:36:24.842-0800] {processor.py:830} INFO - Processing file /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-06T14:36:24.842-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:36:24.842-0800] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:36:24.846-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:36:24.845-0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-06T14:36:24.846-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:36:24.846-0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-06T14:36:24.846-0800] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:36:24.869-0800] {processor.py:183} INFO - Processing /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-01-06T14:36:56.087-0800] {processor.py:161} INFO - Started process (PID=10028) to work on /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:36:56.087-0800] {processor.py:830} INFO - Processing file /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-06T14:36:56.088-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:36:56.088-0800] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:36:56.092-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:36:56.091-0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-06T14:36:56.092-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:36:56.092-0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-06T14:36:56.092-0800] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:36:56.116-0800] {processor.py:183} INFO - Processing /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2024-01-06T14:37:26.681-0800] {processor.py:161} INFO - Started process (PID=10307) to work on /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:37:26.682-0800] {processor.py:830} INFO - Processing file /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-06T14:37:26.683-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:37:26.683-0800] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:37:26.686-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:37:26.686-0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-06T14:37:26.686-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:37:26.686-0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-06T14:37:26.687-0800] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:37:26.713-0800] {processor.py:183} INFO - Processing /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2024-01-06T14:37:57.444-0800] {processor.py:161} INFO - Started process (PID=10505) to work on /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:37:57.445-0800] {processor.py:830} INFO - Processing file /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-06T14:37:57.446-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:37:57.445-0800] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:37:57.449-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:37:57.449-0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-06T14:37:57.450-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:37:57.449-0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-06T14:37:57.450-0800] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:37:57.476-0800] {processor.py:183} INFO - Processing /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-01-06T14:38:28.088-0800] {processor.py:161} INFO - Started process (PID=10679) to work on /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:38:28.089-0800] {processor.py:830} INFO - Processing file /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-06T14:38:28.089-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:38:28.089-0800] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:38:28.093-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:38:28.092-0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-06T14:38:28.093-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:38:28.093-0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-06T14:38:28.093-0800] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:38:28.118-0800] {processor.py:183} INFO - Processing /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-01-06T14:38:59.139-0800] {processor.py:161} INFO - Started process (PID=10870) to work on /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:38:59.140-0800] {processor.py:830} INFO - Processing file /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-06T14:38:59.140-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:38:59.140-0800] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:38:59.144-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:38:59.144-0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-06T14:38:59.144-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:38:59.144-0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-06T14:38:59.145-0800] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:38:59.169-0800] {processor.py:183} INFO - Processing /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-01-06T14:39:29.701-0800] {processor.py:161} INFO - Started process (PID=11029) to work on /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:39:29.702-0800] {processor.py:830} INFO - Processing file /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-06T14:39:29.702-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:39:29.702-0800] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:39:29.706-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:39:29.705-0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-06T14:39:29.706-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:39:29.706-0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-06T14:39:29.706-0800] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:39:29.730-0800] {processor.py:183} INFO - Processing /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2024-01-06T14:40:00.514-0800] {processor.py:161} INFO - Started process (PID=11186) to work on /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:40:00.515-0800] {processor.py:830} INFO - Processing file /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-06T14:40:00.516-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:40:00.516-0800] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:40:00.520-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:40:00.519-0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-06T14:40:00.520-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:40:00.520-0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-06T14:40:00.520-0800] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:40:00.544-0800] {processor.py:183} INFO - Processing /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2024-01-06T14:40:31.277-0800] {processor.py:161} INFO - Started process (PID=11344) to work on /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:40:31.278-0800] {processor.py:830} INFO - Processing file /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-06T14:40:31.279-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:40:31.279-0800] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:40:31.283-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:40:31.282-0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-06T14:40:31.283-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:40:31.283-0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-06T14:40:31.283-0800] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:40:31.308-0800] {processor.py:183} INFO - Processing /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-01-06T14:41:02.228-0800] {processor.py:161} INFO - Started process (PID=11527) to work on /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:41:02.230-0800] {processor.py:830} INFO - Processing file /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-06T14:41:02.230-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:41:02.230-0800] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:41:02.234-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:41:02.234-0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-06T14:41:02.234-0800] {logging_mixin.py:188} INFO - [2024-01-06T14:41:02.234-0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-06T14:41:02.234-0800] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-06T14:41:02.259-0800] {processor.py:183} INFO - Processing /mnt/c/Users/victo/OneDrive/Desktop/fantasy_nba_dashboard/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
